
  {
                "sid": 123,
                "sname": "deepika",
          
                  "city": "VSPK",
                  "state": "AP",
                  "country": "India",
                
                "email": "deep123@gmail.com"
}
