[
  {
                "sid": 123,
                "sname": "deepika",
                "city": "VSPK",
                "state": "AP",
                "country": "India",
                "email": "deep123@gmail.com"
},
{
                "sid": 127,
                "sname": "vennela",
                "city": "VZM",
                "state": "AP",
                "country": "India",
                "email": "venni123@gmail.com"
}

]